### PR TITLE
update DK to 4.2.0

### PR DESCRIPTION
**Pull request by joelhandwell**
### Description

update DK to 4.2.0

### CODE REVIEW

**Comment by gep13** [comment]
@joelhandwell I just tried these two URL's:

* https://packages.chef.io/files/stable/chefdk/$version/windows/2012r2/chefdk-4.2.0-1-x86.msi
* https://packages.chef.io/files/stable/chefdk/$version/windows/2012r2/chefdk-4.2.0-1-x64.msi

And both of them resulted in a 404 response.

**Comment by joelhandwell** [comment]
@gep13 You have to replace both occurrence of ```$version``` with 4.2.0 in those urls.
So instead ```https://packages.chef.io/files/stable/chefdk/$version/windows/2012r2/chefdk-4.2.0-1-x86.msi``` 

use ```https://packages.chef.io/files/stable/chefdk/4.2.0/windows/2012r2/chefdk-4.2.0-1-x86.msi```

This url can be found in Download button in page https://downloads.chef.io/chefdk#windows

**Comment by gep13** [comment]
>@joelhandwell said...
You have to replace both occurrence of $version with 4.2.0 in those urls.

DOH!  Completely missed that!  Thanks for pointing that out!

Initially when I saw your changes, I was concerned that the changes to the base URL, i.e. from

https://packages.chef.io/files/stable

to:

https://packages.chef.io/stable

Would cause older Chocolatey package versions to fail, but when I tested, they still worked, and only had one replacement in them, so I just assumed that was still the case for the new URL's as well.

Thanks for submitting this PR!

**Comment by joelhandwell** [comment]
@tas50 Is there anything I can do for this PR to be merged?

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by tas50** [comment]
Thanks @joelhandwell

**Pull request merged**
